services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: senhadev
    ports:
      - 5432:5432
    volumes:
      - databasedata:/var/lib/postgresql

volumes:
  databasedata:
