service: places
frameworkVersion: '3'

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs20.x
  stage: api
  timeout: 30

functions:
  listPlaces:
    handler: ports/listPlaces.handler
    memorySize: 128
    events:
      - http:
          method: GET
          path: /places/

  getPlace:
    handler: ports/getPlace.handler
    memorySize: 128
    events:
      - http:
          method: GET
          path: /places/{slug}

  createPlace:
    handler: ports/createPlace.handler
    memorySize: 128
    events:
      - http:
          method: POST
          path: /places/

  reviewPatch:
    memorySize: 512
    handler: ports/reviewPatch.handler

custom:
  serverless-offline: ${file(../offlineConfig.yml):services.places}

plugins:
  - serverless-esbuild
  - serverless-offline

