service: places
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: api
  timeout: 30

functions:
  addPlaceReviews:
    handler: ports/addPlaceReviews.handler

custom:
  serverless-offline: ${file(../offlineConfig.yml):services.places}

plugins:
  - serverless-esbuild
  - serverless-offline

