service: scraper
frameworkVersion: '3'

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs20.x
  stage: api
  timeout: 30
  environment:
    scraperPort: ${file(../offlineConfig.yml):services.scraper.lambdaPort}
    placesPort: ${file(../offlineConfig.yml):services.places.lambdaPort}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
          Resource:
            - '*'
        - Effect: 'Allow'
          Action:
            - 'execute-api:Invoke'
          Resource:
            - '*'


functions:
  scheduled:
    handler: ports/schedule.run
    memorySize: 128
    events:
      # - schedule: rate(5 minutes)
        # - schedule: rate(1 hour)
      - http:
          method: GET
          path: /run

  processor:
    handler: ports/processor.handler
    memorySize: 1024
    timeout: 300
    package:
      individually: true
      patterns:
        - "node_modules/.browsers/**"

  mapper:
    handler: ports/mapper.handler
    memorySize: 512
    timeout: 300


package:
  individually: true

custom:
  serverless-offline: ${file(../offlineConfig.yml):services.scraper}
  esbuild:
    bundle: true
    minify: false


plugins:
  - serverless-esbuild
  - serverless-offline
