service: scraper
frameworkVersion: '3'

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs20.x
  stage: api
  timeout: 30
  environment:
    scraperPort: ${file(../offlineConfig.yml):services.scraper.lambdaPort}
    placesPort: ${file(../offlineConfig.yml):services.places.lambdaPort}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
          Resource:
            - '*'
        - Effect: 'Allow'
          Action:
            - 'execute-api:Invoke'
          Resource:
            - '*'


# layers:
#   BrowserPuppeteer:
#     name: chrome-layer
#     description: Puppeteer Browsers Layer
#     compatibleRuntimes:
#       - nodejs20.x
#     path: 'node_modules/.browsers/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/'
#
#

functions:
  scheduled:
    handler: ports/schedule.run
    memorySize: 128
    events:
      - schedule: rate(5 minutes)
        # - schedule: rate(1 hour)
      - http:
          method: GET
          path: /run

  processor:
    handler: ports/processor.handler
    memorySize: 512
    timeout: 300
      # layers:
      # - { Ref: BrowserPuppeteerLambdaLayer }

  mapper:
    handler: ports/mapper.handler
    memorySize: 512
    timeout: 300


package:
  individually: true
  # patterns:
  #   - 'node_modules/.browsers/puppeteer/chrome/linux-119.0.6045.105/chrome-linux64/chrome'

custom:
  serverless-offline: ${file(../offlineConfig.yml):services.scraper}
  esbuild:
    bundle: true
    minify: false



plugins:
  - serverless-esbuild
  - serverless-offline
