service: scraper
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: api
  timeout: 120
  environment:
    processorPort: ${file(../offlineConfig.yml):services.processor.lambdaPort}

functions:
  scheduled:
    handler: ports/webScraper.run
    events:
      # Invoke Lambda function every 5 minutes
      - schedule: rate(1 minute)

custom:
  serverless-offline: ${file(../offlineConfig.yml):services.scraper}


plugins:
  - serverless-esbuild
  - serverless-offline
