service: scraper
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: api
  timeout: 120

functions:
  scheduled:
    handler: ports/webScraper.run
    events:
      # Invoke Lambda function every 5 minutes
      - schedule: rate(5 minutes)

custom:
  serverless-offline:
    # httpPort: ${file(../offlineConfig.yml):services.serviceName.httpPort}
    httpPort: 5001
    lambdaPort: 15001


plugins:
  - serverless-esbuild
  - serverless-offline
