service: scraper
frameworkVersion: '3'

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs20.x
  stage: api
  timeout: 300
  environment:
    scraperPort: ${file(../offlineConfig.yml):services.scraper.lambdaPort}
    placesPort: ${file(../offlineConfig.yml):services.places.lambdaPort}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
          Resource:
            - '*'
        - Effect: 'Allow'
          Action:
            - 'execute-api:Invoke'
          Resource:
            - '*'



functions:
  scheduled:
    handler: ports/schedule.run
    events:
      # - schedule: rate(5 minutes)
      - schedule: rate(1 hour)
      - http:
          method: GET
          path: /run

  processor:
    handler: ports/processor.handler

  mapper:
    handler: ports/mapper.handler



custom:
  serverless-offline: ${file(../offlineConfig.yml):services.scraper}


plugins:
  - serverless-esbuild
  - serverless-offline
